version: '3.4'

services:
  sapex:
    image: ${DOCKER_REGISTRY-}sapex
    build:
      context: .
      dockerfile: SAPex/Dockerfile

  sapexschedulerservice:
    image: ${DOCKER_REGISTRY-}sapexschedulerservice
    build:
      context: .
      dockerfile: SAPexSchedulerService/Dockerfile

