version: '3.4'

services:
  sapex:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - MSSQL_CONNECTION_STRING=Server=db,1433;Database=master;User Id=SA;Password=MyPass@word
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on: 
      - db

  db:
    image : "mcr.microsoft.com/azure-sql-edge"
    ports :
      - "1433:1433"
    environment:
       MSSQL_PID : "Developer"
       MSSQL_USER : "SA"
       MSSQL_SA_PASSWORD : "MyPass@word"
       ACCEPT_EULA: "Y"
