// <auto-generated />
using System;
using DbMigrations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbMigrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211031094633_AddAllUpdatedTables")]
    partial class AddAllUpdatedTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbMigrations.EntityModels.AccessEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accesses");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.AccessFormEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FunctionalRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.HasIndex("FormId");

                    b.HasIndex("FunctionalRoleId");

                    b.ToTable("AccessForms");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateLanguageEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageLevelId");

                    b.ToTable("CandidateLanguages");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateProccesEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TestResult")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("StatusId");

                    b.ToTable("CandidatesProcceses");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateProjectRoleEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CandidateProjectRoles");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateSandboxEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProccesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProjectRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SandboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StackTechnologiesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CandidateProccesId");

                    b.HasIndex("CandidateProjectRoleId");

                    b.HasIndex("SandboxId");

                    b.HasIndex("StackTechnologiesId");

                    b.HasIndex("TeamId");

                    b.ToTable("CandidateSandboxes");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateTechSkillEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateTechSkills");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FeedbackEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserReview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FormEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FunctionalRoleEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FunctionalRoles");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.LanguageEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.LanguageLevelEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LanguageLevels");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.RatingEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SandboxEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndRegistration")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxCandidates")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartRegistration")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sandboxes");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SandboxStackTechnologyEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SandboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StackTechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SandboxId");

                    b.HasIndex("StackTechnologyId");

                    b.ToTable("SandboxStackTechnologies");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SkillEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.StackTechnologyEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StackTechnologies");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.StatusEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.TeamEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SandboxId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SandboxId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserFunctionalRoleEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FunctionalRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FunctionalRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFunctionalRoles");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserLanguageEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageLevelId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserSandBoxEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FunctionalRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SandBoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SandBoxId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSandBoxes");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserStackTechnologyEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StackTechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StackTechnologyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserStackTechnologies");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserTeamEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserSandBoxId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserSandBoxId");

                    b.ToTable("UserTeams");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserTechSkillEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTechSkills");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.AccessFormEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.AccessEntityModel", "Access")
                        .WithMany("AccessForms")
                        .HasForeignKey("AccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.FormEntityModel", "Form")
                        .WithMany("AccessForms")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.FunctionalRoleEntityModel", "FunctionalRole")
                        .WithMany("AccessForms")
                        .HasForeignKey("FunctionalRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access");

                    b.Navigation("Form");

                    b.Navigation("FunctionalRole");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateLanguageEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.CandidateEntityModel", "Candidate")
                        .WithMany("CandidateLanguages")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.LanguageEntityModel", "Language")
                        .WithMany("CandidateLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.LanguageLevelEntityModel", "LanguageLevel")
                        .WithMany("CandidateLanguages")
                        .HasForeignKey("LanguageLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Language");

                    b.Navigation("LanguageLevel");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateProccesEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.FeedbackEntityModel", "Feedback")
                        .WithMany("CandidateProcceses")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.StatusEntityModel", "Status")
                        .WithMany("CandidatesProcceses")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateSandboxEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.CandidateEntityModel", "Candidate")
                        .WithMany("CandidateSandboxes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.CandidateProccesEntityModel", "CandidateProcces")
                        .WithMany()
                        .HasForeignKey("CandidateProccesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.CandidateProjectRoleEntityModel", "CandidateProjectRole")
                        .WithMany("CandidateSandboxes")
                        .HasForeignKey("CandidateProjectRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.SandboxEntityModel", "Sandbox")
                        .WithMany("CandidateSandboxes")
                        .HasForeignKey("SandboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.StackTechnologyEntityModel", "StackTechnologies")
                        .WithMany("CandidateSandboxes")
                        .HasForeignKey("StackTechnologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.TeamEntityModel", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("CandidateProcces");

                    b.Navigation("CandidateProjectRole");

                    b.Navigation("Sandbox");

                    b.Navigation("StackTechnologies");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateTechSkillEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.CandidateEntityModel", "Candidate")
                        .WithMany("CandidateTechSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.SkillEntityModel", "Skill")
                        .WithMany("CandidateTechSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FeedbackEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.RatingEntityModel", "Rating")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.RatingEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.SkillEntityModel", "Skill")
                        .WithMany("Ratings")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SandboxStackTechnologyEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.SandboxEntityModel", "Sandbox")
                        .WithMany("SandboxStackTechnologies")
                        .HasForeignKey("SandboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.StackTechnologyEntityModel", "StackTechnology")
                        .WithMany("SandboxStackTechnologies")
                        .HasForeignKey("StackTechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sandbox");

                    b.Navigation("StackTechnology");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.TeamEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.SandboxEntityModel", "Sandbox")
                        .WithMany("Teams")
                        .HasForeignKey("SandboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sandbox");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserFunctionalRoleEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.FunctionalRoleEntityModel", "FunctionalRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("FunctionalRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FunctionalRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserLanguageEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.LanguageEntityModel", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.LanguageLevelEntityModel", "LanguageLevel")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("LanguageLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserSandBoxEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.SandboxEntityModel", "Sandbox")
                        .WithMany("UserSandboxes")
                        .HasForeignKey("SandBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany("UserSanboxes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sandbox");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserStackTechnologyEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.StackTechnologyEntityModel", "StackTechnology")
                        .WithMany("UserStackTechnologies")
                        .HasForeignKey("StackTechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany("UserStackTechnologies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StackTechnology");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserTeamEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.TeamEntityModel", "Team")
                        .WithMany("UserTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserSandBoxEntityModel", "UserSandBox")
                        .WithMany("UserTeams")
                        .HasForeignKey("UserSandBoxId")
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("UserSandBox");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserTechSkillEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.SkillEntityModel", "Skill")
                        .WithMany("UserTechSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany("UserTechSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.AccessEntityModel", b =>
                {
                    b.Navigation("AccessForms");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateEntityModel", b =>
                {
                    b.Navigation("CandidateLanguages");

                    b.Navigation("CandidateSandboxes");

                    b.Navigation("CandidateTechSkills");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateProjectRoleEntityModel", b =>
                {
                    b.Navigation("CandidateSandboxes");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FeedbackEntityModel", b =>
                {
                    b.Navigation("CandidateProcceses");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FormEntityModel", b =>
                {
                    b.Navigation("AccessForms");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FunctionalRoleEntityModel", b =>
                {
                    b.Navigation("AccessForms");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.LanguageEntityModel", b =>
                {
                    b.Navigation("CandidateLanguages");

                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.LanguageLevelEntityModel", b =>
                {
                    b.Navigation("CandidateLanguages");

                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.RatingEntityModel", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SandboxEntityModel", b =>
                {
                    b.Navigation("CandidateSandboxes");

                    b.Navigation("SandboxStackTechnologies");

                    b.Navigation("Teams");

                    b.Navigation("UserSandboxes");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SkillEntityModel", b =>
                {
                    b.Navigation("CandidateTechSkills");

                    b.Navigation("Ratings");

                    b.Navigation("UserTechSkills");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.StackTechnologyEntityModel", b =>
                {
                    b.Navigation("CandidateSandboxes");

                    b.Navigation("SandboxStackTechnologies");

                    b.Navigation("UserStackTechnologies");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.StatusEntityModel", b =>
                {
                    b.Navigation("CandidatesProcceses");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.TeamEntityModel", b =>
                {
                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserEntityModel", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSanboxes");

                    b.Navigation("UserStackTechnologies");

                    b.Navigation("UserTechSkills");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserSandBoxEntityModel", b =>
                {
                    b.Navigation("UserTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
