// <auto-generated />
using System;
using DbMigrations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbMigrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbMigrations.EntityModels.AccessEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accesses");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.AccessFormEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FunctionalRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.HasIndex("FormId");

                    b.HasIndex("FunctionalRoleId");

                    b.ToTable("AccessForms");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.AvailabilityTypeEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AvailabilityTypes");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CalendarEventEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InterviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InterviewerId");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionaCertificates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateLanguageEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageLevelId");

                    b.ToTable("CandidateLanguages");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateProccesEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateSandboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TestResult")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateSandboxId");

                    b.HasIndex("StatusId");

                    b.ToTable("CandidatesProcceses");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateProjectRoleEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CandidateProjectRoles");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateSandboxEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AvailabilityTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CandidateProjectRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAgreement")
                        .HasColumnType("bit");

                    b.Property<bool>("IsJoinToExadel")
                        .HasColumnType("bit");

                    b.Property<string>("Motivation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SandboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SandboxLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StackTechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeContact")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityTypeId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CandidateProjectRoleId");

                    b.HasIndex("SandboxId");

                    b.HasIndex("StackTechnologyId");

                    b.HasIndex("TeamId");

                    b.ToTable("CandidateSandboxes");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateTechSkillEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateTechSkills");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FeedbackEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProccesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Grade")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserReview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProccesId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FileEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FormEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FunctionalRoleEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FunctionalRoles");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.GoogleAccessTokenEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Access_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Created_in")
                        .HasColumnType("bigint");

                    b.Property<long>("Expires_in")
                        .HasColumnType("bigint");

                    b.Property<string>("Refresh_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GoogleAccessTokens");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.InterviewEventEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateSandboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CalendarEventId");

                    b.HasIndex("CandidateSandboxId");

                    b.ToTable("InterviewEvents");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.LanguageEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.LanguageLevelEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LanguageLevels");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.LocationEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SandboxEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndRegistration")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxCandidates")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartRegistration")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sandboxes");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SandboxLanguageEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SandboxId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("SandboxId");

                    b.ToTable("SandboxLanguages");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SandboxStackTechnologyEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SandboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StackTechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SandboxId");

                    b.HasIndex("StackTechnologyId");

                    b.ToTable("SandboxStackTechnologies");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SkillEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.StackTechnologyEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StackTechnologies");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.StatusEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.TeamEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SandboxId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SandboxId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserFunctionalRoleEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FunctionalRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FunctionalRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFunctionalRoles");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserLanguageEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageLevelId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserRefreshTokenEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserSandBoxEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SandBoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SandBoxId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSandBoxes");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserStackTechnologyEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StackTechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StackTechnologyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserStackTechnologies");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserTeamEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserSandBoxId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserSandBoxId");

                    b.ToTable("UserTeams");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserTechSkillEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTechSkills");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.AccessFormEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.AccessEntityModel", "Access")
                        .WithMany("AccessForms")
                        .HasForeignKey("AccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.FormEntityModel", "Form")
                        .WithMany("AccessForms")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.FunctionalRoleEntityModel", "FunctionalRole")
                        .WithMany("AccessForms")
                        .HasForeignKey("FunctionalRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access");

                    b.Navigation("Form");

                    b.Navigation("FunctionalRole");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CalendarEventEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany()
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.LocationEntityModel", "Location")
                        .WithMany("Candidates")
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateLanguageEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.CandidateEntityModel", "Candidate")
                        .WithMany("CandidateLanguages")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.LanguageEntityModel", "Language")
                        .WithMany("CandidateLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.LanguageLevelEntityModel", "LanguageLevel")
                        .WithMany("CandidateLanguages")
                        .HasForeignKey("LanguageLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Language");

                    b.Navigation("LanguageLevel");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateProccesEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.CandidateSandboxEntityModel", "CandidateSandbox")
                        .WithMany("CandidateProcesses")
                        .HasForeignKey("CandidateSandboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.StatusEntityModel", "Status")
                        .WithMany("CandidatesProcceses")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateSandbox");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateSandboxEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.AvailabilityTypeEntityModel", "AvailabilityType")
                        .WithMany("CandidateSandboxes")
                        .HasForeignKey("AvailabilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.CandidateEntityModel", "Candidate")
                        .WithMany("CandidateSandboxes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.CandidateProjectRoleEntityModel", "CandidateProjectRole")
                        .WithMany("CandidateSandboxes")
                        .HasForeignKey("CandidateProjectRoleId");

                    b.HasOne("DbMigrations.EntityModels.SandboxEntityModel", "Sandbox")
                        .WithMany("CandidateSandboxes")
                        .HasForeignKey("SandboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.StackTechnologyEntityModel", "StackTechnology")
                        .WithMany("CandidateSandboxes")
                        .HasForeignKey("StackTechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.TeamEntityModel", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("AvailabilityType");

                    b.Navigation("Candidate");

                    b.Navigation("CandidateProjectRole");

                    b.Navigation("Sandbox");

                    b.Navigation("StackTechnology");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateTechSkillEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.CandidateEntityModel", "Candidate")
                        .WithMany("CandidateTechSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.SkillEntityModel", "Skill")
                        .WithMany("CandidateTechSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FeedbackEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.CandidateProccesEntityModel", "CandidateProcces")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CandidateProccesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProcces");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.GoogleAccessTokenEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.InterviewEventEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.CalendarEventEntityModel", "CalendarEvent")
                        .WithMany("InterviewEvents")
                        .HasForeignKey("CalendarEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.CandidateSandboxEntityModel", "CandidateSandbox")
                        .WithMany()
                        .HasForeignKey("CandidateSandboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarEvent");

                    b.Navigation("CandidateSandbox");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SandboxLanguageEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.LanguageEntityModel", "Language")
                        .WithMany("SandboxLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.SandboxEntityModel", "Sandbox")
                        .WithMany("SandboxLanguages")
                        .HasForeignKey("SandboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Sandbox");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SandboxStackTechnologyEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.SandboxEntityModel", "Sandbox")
                        .WithMany("SandboxStackTechnologies")
                        .HasForeignKey("SandboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.StackTechnologyEntityModel", "StackTechnology")
                        .WithMany("SandboxStackTechnologies")
                        .HasForeignKey("StackTechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sandbox");

                    b.Navigation("StackTechnology");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.TeamEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.SandboxEntityModel", "Sandbox")
                        .WithMany("Teams")
                        .HasForeignKey("SandboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sandbox");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.LocationEntityModel", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserFunctionalRoleEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.FunctionalRoleEntityModel", "FunctionalRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("FunctionalRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FunctionalRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserLanguageEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.LanguageEntityModel", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.LanguageLevelEntityModel", "LanguageLevel")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("LanguageLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserRefreshTokenEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserSandBoxEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.SandboxEntityModel", "Sandbox")
                        .WithMany("UserSandboxes")
                        .HasForeignKey("SandBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany("UserSanboxes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sandbox");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserStackTechnologyEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.StackTechnologyEntityModel", "StackTechnology")
                        .WithMany("UserStackTechnologies")
                        .HasForeignKey("StackTechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany("UserStackTechnologies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StackTechnology");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserTeamEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.TeamEntityModel", "Team")
                        .WithMany("UserTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserSandBoxEntityModel", "UserSandBox")
                        .WithMany("UserTeams")
                        .HasForeignKey("UserSandBoxId")
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("UserSandBox");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserTechSkillEntityModel", b =>
                {
                    b.HasOne("DbMigrations.EntityModels.SkillEntityModel", "Skill")
                        .WithMany("UserTechSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbMigrations.EntityModels.UserEntityModel", "User")
                        .WithMany("UserTechSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.AccessEntityModel", b =>
                {
                    b.Navigation("AccessForms");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.AvailabilityTypeEntityModel", b =>
                {
                    b.Navigation("CandidateSandboxes");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CalendarEventEntityModel", b =>
                {
                    b.Navigation("InterviewEvents");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateEntityModel", b =>
                {
                    b.Navigation("CandidateLanguages");

                    b.Navigation("CandidateSandboxes");

                    b.Navigation("CandidateTechSkills");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateProccesEntityModel", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateProjectRoleEntityModel", b =>
                {
                    b.Navigation("CandidateSandboxes");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.CandidateSandboxEntityModel", b =>
                {
                    b.Navigation("CandidateProcesses");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FormEntityModel", b =>
                {
                    b.Navigation("AccessForms");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.FunctionalRoleEntityModel", b =>
                {
                    b.Navigation("AccessForms");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.LanguageEntityModel", b =>
                {
                    b.Navigation("CandidateLanguages");

                    b.Navigation("SandboxLanguages");

                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.LanguageLevelEntityModel", b =>
                {
                    b.Navigation("CandidateLanguages");

                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.LocationEntityModel", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SandboxEntityModel", b =>
                {
                    b.Navigation("CandidateSandboxes");

                    b.Navigation("SandboxLanguages");

                    b.Navigation("SandboxStackTechnologies");

                    b.Navigation("Teams");

                    b.Navigation("UserSandboxes");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.SkillEntityModel", b =>
                {
                    b.Navigation("CandidateTechSkills");

                    b.Navigation("UserTechSkills");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.StackTechnologyEntityModel", b =>
                {
                    b.Navigation("CandidateSandboxes");

                    b.Navigation("SandboxStackTechnologies");

                    b.Navigation("UserStackTechnologies");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.StatusEntityModel", b =>
                {
                    b.Navigation("CandidatesProcceses");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.TeamEntityModel", b =>
                {
                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserEntityModel", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSanboxes");

                    b.Navigation("UserStackTechnologies");

                    b.Navigation("UserTechSkills");
                });

            modelBuilder.Entity("DbMigrations.EntityModels.UserSandBoxEntityModel", b =>
                {
                    b.Navigation("UserTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
